### PR TITLE
Tillerless Helm

### LINKED ISSUE #20: Helm 'unauthorized' error after repeated make uninstalls
When uninstalling various addons in (possibly) an incorrect order, `helm` loses `kube-system` perissions/access and returns the following unhelpful error message:

```
helm list
Error: Unauthorized
```

Once `helm` gets into this state, deleting and re-installing `helm` doesn't help.

### LINKED ISSUE #26: Investigate "tiller-less" Helm
Investigate using https://rimusz.net/tillerless-helm/ --- we may want to switch to this as it offers some huge benefits over running `tiller` in every namespace. 

Things we'd need to add:
- [ ] env var setup and validation
- [ ] changes to the existing `helm` addon
- [ ] fix the shell out repo change, so it stays in the addon makefile.
- [ ] install [plugin](https://github.com/rimusz/helm-tiller) in addon
- [ ] verify tiller server is starts and stops after install.
- [ ] update readme.

### PR DESCRIPTION
**Pull request by tlake**
Tasks from the issue:
- [x] env var setup and validation
- [x] changes to the existing helm addon
    - The existing helm addon has actually been deleted entirely. The installation of local-use tiller is delegated to the user much like the other binaries that we list as dependencies.
- [ ] fix the shell out repo change, so it stays in the addon makefile
    - I'm not entirely sure what this refers to.
- ~[ ] install plugin in addon~
    - The tillerless helm plugin is a user's responsibility, like binaries and env vars.
- [x] verify tiller server is starts and stops after install
    - Using `helm tiller run` ensures that the local tiller is terminated after the command is run.
- [x] update readme

closes #26 (and closes #20 by extension, since we no longer should be worrying about helm's authorization)

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -1,8 +1,10 @@
+HERE=$(CURDIR)
```
Comment (nehayward) [inline Makefile]: Maybe a more descriptive name, `WORKDIR` or `EKS`

File: scripts/check-environment.sh [hunk 2]
```diff
@@ -28,6 +30,14 @@ compare_versions() {
     fi
 }
 
+if [ "$(helm plugin list | grep tiller | awk '{ print $1 }')" == "" ]; then
+    echo "Couldn't find the Tillerless Helm plugin."
+    exit 1
+fi
+
+CUR_TILLERLESS_HELM_VERSION=$(helm plugin list | grep tiller | awk '{ print $2 }')
```
Comment (nehayward) [inline scripts/check-environment.sh]: Nice!

File: Makefile (hunk 1 above)
Comment (tlake) [inline Makefile]: ambiguous name

Comment (diemonster) [reply Makefile]: might as well just use $(CURDIR) across the board

File: README.md [hunk 3]
```diff
@@ -8,6 +8,7 @@ This example shows how one can integrate the [AWS VPC](https://registry.terrafor
 * [Kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/) (>= v1.10.4) installed and in your local machine's PATH
 * [Heptio Authenticator](https://github.com/heptio/authenticator) (>= v0.3.0) installed and in your local machine's PATH. Currently, this binary needs to be renamed to `aws-iam-authenticator` after being placed in your PATH.
 * [Helm](https://github.com/kubernetes/helm) (>=v2.9.0) installed and in your local machine's PATH.
+* [Tillerless Helm](https://github.com/rimusz/helm-tiller) plugin for helm installed.
```
Comment (diemonster) [inline README.md]: I think we should call this something more akin to "Local Tiller" since that's what's actually happening. We aren't really removing tiller per se, just changing where it runs from.

File: scripts/check-environment.sh [hunk 4]
```diff
@@ -28,6 +30,14 @@ compare_versions() {
     fi
 }
 
+if [ "$(helm plugin list | grep tiller | awk '{ print $1 }')" == "" ]; then
+    echo "Couldn't find the Tillerless Helm plugin."
```
Comment (diemonster) [inline scripts/check-environment.sh]: ditto re: "Tillerless Helm"

File: README.md (hunk 3 above)
Comment (diemonster) [reply README.md]: Dovetailing off this, I wonder if we should discuss a bit in the README that Tiller runs locally and communicates with the k8s API and therefore needs certain port allowances? Not sure where to draw the line with abstracting those details...

File: Makefile (hunk 1 above)
Comment (tlake) [reply Makefile]: I'll just use `$(CURDIR)` itself as per @diemonster's suggestion

✅

File: README.md (hunk 3 above)
Comment (tlake) [reply README.md]: ✅

File: scripts/check-environment.sh (hunk 4 above)
Comment (tlake) [reply scripts/check-environment.sh]: ✅
